test output of csv
bensialih/algeria-cities pull request #185
Opened 2024-05-26 12:28 UTC by bensialih

test conversion script from json to csv

2024-05-26 17:24 UTC, seddik commented
could you trim this, and make the script replaces quotes then trim, not trim then replace quotes.


![image](https://github.com/bensialih/algeria-cities/assets/6674347/bae62d39-3bb2-4a44-9231-68bfa8c592be)

2024-05-26 17:27 UTC, seddik commented
@bensialih  there is the double space also we have 34 cases, so please add it to the script after removing the quotes
1- remove quotes
2- replace double spaces
3- trim (Left & Right)

![image](https://github.com/bensialih/algeria-cities/assets/6674347/a348e6b2-fe1d-49ab-8a2a-6ad9cca0bbf2)

2024-06-09 19:37 UTC, seddik requested changes
@bensialih for the first file  it looks GOOD 👍✅ `csv/algeria_cities_export.csv]`

for the other ones they are made with the old script I think
1- I think we need to get rid of the double quotes "
2- there are places with **double space**

2024-06-09 20:18 UTC, bensialih commented
@seddik  I will have a look this hopefully on Wednesday or next weekend. Hopefully next weekend I will make some more changes

2024-06-15 15:16 UTC, bensialih commented on csv/algeria_postcodes_export.csv
> +03048,"الأغواط - ""DCA""",Laghouat D C A,"الأغواط - ""DCA""",Laghouat Dca,79,الأغواط,Laghouat,الأغواط,Laghouat,03,الأغواط,Laghouat
I think things like these double quotes are present in the Json payload too.
These are put in when double quotes are part of the entry and should be looked into as possible flaws for that entry.

2024-06-15 15:19 UTC, bensialih commented on csv/algeria_postcodes_export.csv
> +03048,"الأغواط - ""DCA""",Laghouat D C A,"الأغواط - ""DCA""",Laghouat Dca,79,الأغواط,Laghouat,الأغواط,Laghouat,03,الأغواط,Laghouat
I think we should stop here and not do any more formatting. I worry we are experiencing mission creep.

I think maybe formatting should be its own separate objective.

2024-06-15 15:23 UTC, bensialih commented on csv/algeria_postcodes_export.csv
> +03048,"الأغواط - ""DCA""",Laghouat D C A,"الأغواط - ""DCA""",Laghouat Dca,79,الأغواط,Laghouat,الأغواط,Laghouat,03,الأغواط,Laghouat
quotes pertaining to preceding or trailing spaces disappear when these spaces are removed but as stayed above, other scenarios may need to be addressed.

2024-07-21 15:44 UTC, merged